# Generated by Django 5.2.7 on 2025-11-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='strategy_images/'),
        ),
    ]
